// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PromptService 提示词管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeletePrompt 删除提示词
 */
export function DeletePrompt(platform: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.PromptService.DeletePrompt", platform, id);
}

/**
 * EnablePrompt 启用指定提示词（会禁用其他所有提示词）
 */
export function EnablePrompt(platform: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.PromptService.EnablePrompt", platform, id);
}

/**
 * GetCurrentFileContent 获取当前提示词文件内容
 */
export function GetCurrentFileContent(platform: string): $CancellablePromise<string | null> {
    return $Call.ByName("codeswitch/services.PromptService.GetCurrentFileContent", platform);
}

/**
 * GetPrompts 获取指定平台的所有提示词
 */
export function GetPrompts(platform: string): $CancellablePromise<{ [_ in string]?: $models.Prompt }> {
    return $Call.ByName("codeswitch/services.PromptService.GetPrompts", platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromFile 从现有文件导入提示词
 */
export function ImportFromFile(platform: string): $CancellablePromise<string> {
    return $Call.ByName("codeswitch/services.PromptService.ImportFromFile", platform);
}

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.PromptService.Start");
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.PromptService.Stop");
}

/**
 * UpsertPrompt 添加或更新提示词
 */
export function UpsertPrompt(platform: string, id: string, prompt: $models.Prompt): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.PromptService.UpsertPrompt", platform, id, prompt);
}

// Private type creation functions
const $$createType0 = $models.Prompt.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
