// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DuplicateProvider 复制供应商配置，生成新的副本
 * 返回新创建的 Provider 对象
 */
export function DuplicateProvider(kind: string, sourceID: number): $CancellablePromise<$models.Provider | null> {
    return $Call.ByName("codeswitch/services.ProviderService.DuplicateProvider", kind, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadProviders(kind: string): $CancellablePromise<$models.Provider[]> {
    return $Call.ByName("codeswitch/services.ProviderService.LoadProviders", kind).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveProviders(kind: string, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.ProviderService.SaveProviders", kind, providers);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.ProviderService.Start");
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByName("codeswitch/services.ProviderService.Stop");
}

// Private type creation functions
const $$createType0 = $models.Provider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
